### ISSUE TITLE
which package to use

### ISSUE THREAD

**Issue by bsr203** [go-errgo/errgo#1]
Hi rog,

I like to use one of many errgo packages :-)

https://launchpad.net/errgo/
or this repo. I see a v2 in launchpad branch, which is better?

which one you plan to maintain, and best to use.

Thanks,
bsr

**Comment by rogpeppe** [comment]
The one to use is gopkg.in/errgo.v1. I think the licence there should be ok
for you.

Sorry for the proliferation of places... I need to clean them up!

  Cheers, rog.

**Comment by bsr203** [comment]
thanks for the help.
